tools:
    php_sim: false
    php_pdepend: true
    php_analyzer: true
    php_code_coverage: true
    external_code_coverage: false

build:
    nodes:
        php73:
            environment:
                postgresql: false
                redis: false
                php:
                    version: 7.3.23
            tests:
                override:
                    -
                        command: 'vendor/phpunit/phpunit/phpunit --coverage-clover=tests/cover'
                        coverage:
                            file: 'tests/cover'
                            format: php-clover
        php74:
            environment:
                postgresql: false
                redis: false
                php:
                    version: 7.4.11
            tests:
                override:
                    -
                        command: 'vendor/phpunit/phpunit/phpunit --coverage-clover=tests/cover'
                        coverage:
                            file: 'tests/cover'
                            format: php-clover
    environment:
        postgresql: false
        redis: false
        php:
            version: 7.4.11
    tests:
        override:
            -
                command: 'vendor/phpunit/phpunit/phpunit --coverage-clover=tests/cover'
                coverage:
                    file: 'tests/cover'
                    format: php-clover

filter:
    excluded_paths: [vendor/*, tests/*, examples/*]